apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
    targetRevision: v0.6.4
    path: deploy/ha
  destination:
    server: https://kubernetes.default.svc
    namespace: kubelet-serving-cert-approver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deedoubledub/homelab.git
    targetRevision: HEAD
    path: base/metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
